### ISSUE TITLE
Make Expiration optional

### ISSUE THREAD

**Issue by mdissel** [jesuslpm/Logging.Raven#2]
https://github.com/jesuslpm/Logging.Raven/blob/ca18bb00bbe0beeab9dde10212581a818cf19a37/Logging.Raven/RavenLoggerProcessor.cs#L129

I would suggest to make the Expiration optional.

Thanks

**Comment by jesuslpm** [comment]
Thanks for the suggestion.

I believe logs should expire, otherwise database would become huge overtime.
Expiration defaults to 4 days if not specified, you can specify the value you want, for example 50 years, and the database may have expiration disabled.

Why should I make expiration optional?

**Comment by mdissel** [comment]
> Why should I make expiration optional?

To allow for no expiration of log files and the expiration feature is an optional feature in RavenDb that can be disabled.

Thanks

**Comment by jesuslpm** [comment]
If you want no expiration just set expiration to 100 years or don't enable expiration on the database. I think this is better than the possibility to forget to specify expiration and got an unwanted huge database.

**Comment by mdissel** [comment]
Agreed! Thanks!
